apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypod
  namespace: mycompany
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mypod
      namespace: myns
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        
  
