apiVersion: v1
kind: Pod
metadata:
  name: mynginxpod1
spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
        - containerPort: 80
      env:
      - name: COLORNAME
        valueFrom: 
         configMapKeyRef:
            name: game-demo
            key: player_initial_lives
